### ISSUE TITLE
Cannot seem to deploy your container

### ISSUE THREAD

**Issue by dfrossouw** [galojix/roster-wizard#9]
ERROR: for roster_web_1  Cannot start service web: Mounts denied: 
The path /opt/roster/static is not shared from the host and is not known to Docker.
Creating roster_celery_1   ... done
See https://docs.docker.com/docker-for-mac for more info.

ERROR: for web  Cannot start service web: Mounts denied: 
The path /opt/roster/static is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/docker-for-mac for more info.
ERROR: Encountered errors while bringing up the project.

**Comment by gregcowell** [comment]
Make sure you are using the installation instructions located here: [https://www.galojix.com/demos/roster/](https://www.galojix.com/demos/roster/). In particular the /opt/roster directory needs to be created and the user that instantiates the containers must have permissions to it.

**Comment by dfrossouw** [comment]
I did it exactly like the instructions. now i get the following 
`Recreating roster_db_1       ... done
Recreating roster_rabbitmq_1 ... done
Creating roster_celery_1     ... 
Creating roster_web_1        ... 
Killed`

**Comment by dfrossouw** [comment]
Might it be a resource issue now?

**Comment by gregcowell** [comment]
It could be. It looks a bit like an out of memory error.

**Comment by dfrossouw** [comment]
Forbidden (403)
CSRF verification failed. Request aborted.
You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.

**Comment by gregcowell** [comment]
This may possibly be due to not configuring the secret key.

**Comment by dfrossouw** [comment]
Thank you for your assistance. All working now. Can't wait to see what it can do

**Comment by dfrossouw** [comment]
One last thing. I Am getting a 500 error when I try to generate a roster. 

All I can see is IndexError: list index out of range

**Comment by gregcowell** [comment]
If you run “docker-compose logs -f celery” before (and while) you attempt to generate a roster, the output should give some indication to what is happening.

**Comment by dfrossouw** [comment]
Thanks for being so on top of things. I got it to work by deleting the days. While I have you, how do you get it to schedule staff to only one shift per day?

**Comment by gregcowell** [comment]
One shift per staff member per day should occur automatically without needing any configuration.

**Comment by dfrossouw** [comment]
What does this really mean: Could not generate roster, try putting more staff on leave or changing rules...
Aside from the 500 error from time to time i cant get a roster made.

**Comment by gregcowell** [comment]
It means that it is not possible to generate a valid roster using the specified staff and rules. For example your staff may need more shifts than actually exist in the roster period. If you are able to create a valid roster manually, then it is possible that you just need to make sure your rules and shifts per staff member per roster period are correct. The output of “docker-compose logs -f celery” may shed some light on the problem.

**Comment by dfrossouw** [comment]
`Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[26315] Failed to execute script docker-compose`

**Comment by gregcowell** [comment]
The user account that you use to run docker-compose needs to be in the docker group so that it has the correct permissions.

**Comment by dfrossouw** [comment]
Yes i have done that. Is there a secure channel where I can share my FQDN and password so you can see why its not allocating all the shifts. BTW We are very interested in having this project customised to suit our needs.

**Comment by dfrossouw** [comment]
So would like to know your availability and rates.
